const products =[
    {
        id: 0,
        name: "Espresso",
        description: "Intensywne espresso z głębokim smakiem i nutą karmelu - doskonałe doznania kawowe w każdym łyku.",
        category: "coffee",
        price: 9 ,
        image: "./images/espresso.jpg",
    },
    {
        id: 1,
        name: "Cappuccino",
        description: "Zanurz się w doskonałym smaku naszego cappuccino - harmonia pianki i intensywnego espresso.",
        category: "coffee",
        price: 11 ,
        image: "./images/cappucino.jpg",
    },
    {
        id: 2,
        name: "Latte",
        description: "Delikatne latte - klasyczna przyjemność w każdym łyku.",
        category: "coffee",
        price: 7 ,
        image: "./images/latte.jpg",
    },
    {
        id: 3,
        name: "Cafe Frappe",
        description: "Odkryj orzeźwiający hit w każdym łyku - nasze cafe frappe to lodowato schłodzone doznanie kawowe.",
        category: "coffee",
        price: 15 ,
        image: "./images/frappe.jpg",
    },
    {
        id: 4,
        name: "Czarna herbata",
        description: "Odkryj klasykę w filiżance - nasza czarna herbata to aromatyczne doznanie o pełnym smaku i energetyzującym charakterze.",
        category: "tea",
        price: 10 ,
        image: "./images/czarna.jpg",
    },
    {
        id: 5,
        name: "Matcha",
        description: "Zanurz się w zielonej harmonii z naszą matchą. Wyjątkowa japońska herbata, bogata w smak i dobroczynne właściwości, zapewniająca unikalne doznania",
        category: "tea",
        price: 17 ,
        image: "./images/matcha.jpg",
    },
    {
        id: 6,
        name: "Zielona herbata",
        description: "Odkryj świeżość w filiżance z naszą zieloną herbatą. Delikatny smak i naturalna energia, które poprawią Twój nastrój i zadbają o Twoje samopoczucie.",
        category: "Coffee",
        price: 15 ,
        image: "./images/zielona.jpg",
    },
    {
        id: 7,
        name: "Sernik z karmelem",
        description: "Rozkoszuj się wyjątkowym doświadczeniem smakowym naszego sernika. Delikatna konsystencja, bogaty smak sera i kruchy spód - prawdziwa uczta dla podniebienia.",
        category: "cake",
        price: 15 ,
        image: "./images/sernik.jpg",
    },
    {
        id: 8,
        name: "Cafe Frappe",
        description: "Zanurz się w nostalgii smaku z naszą szarlotką. Soczyste jabłka, krucha kruszonka i aromat cynamonu - każdy kawałek to podróż do domowego ciepła.",
        category: "cake",
        price: 15 ,
        image: "./images/szarlotka.jpg",
    },
] 
